"""Final standardized Bakugan/card content pack.
Standardized RAW_BAKUGAN_TEMPLATES layout, with only one Angelo/Diablo Preyas entry.
"""

RAW_BAKUGAN_TEMPLATES = [{'name': 'Serpenoid',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [190,
               200,
               210,
               220,
               230,
               240,
               250,
               260,
               270,
               280,
               290,
               300,
               310,
               320,
               330,
               340,
               350,
               360,
               370,
               380,
               390,
               400,
               410,
               420,
               430,
               440],
  'price': 100},
 {'name': 'Juggernoid',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [200,
               210,
               220,
               230,
               240,
               250,
               260,
               270,
               280,
               290,
               300,
               310,
               320,
               330,
               340,
               350,
               360,
               370,
               380,
               390,
               400,
               410,
               420,
               430,
               440,
               450],
  'price': 100},
 {'name': 'Robotallion',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [200,
               210,
               220,
               230,
               240,
               250,
               260,
               270,
               280,
               290,
               300,
               310,
               320,
               330,
               340,
               350,
               360,
               370,
               380,
               390,
               400,
               410,
               420,
               430,
               440,
               450],
  'price': 100},
 {'name': 'Saurus',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [210,
               220,
               230,
               240,
               250,
               260,
               270,
               280,
               290,
               300,
               310,
               320,
               330,
               340,
               350,
               360,
               370,
               380,
               390,
               400,
               410,
               420,
               430,
               440,
               450,
               460],
  'price': 105},
 {'name': 'Falconeer',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [210,
               220,
               230,
               240,
               250,
               260,
               270,
               280,
               290,
               300,
               310,
               320,
               330,
               340,
               350,
               360,
               370,
               380,
               390,
               400,
               410,
               420,
               430,
               440,
               450,
               460],
  'price': 105},
 {'name': 'Manion',
  'allowed_attributes': ['SUBTERRA', 'HAOS', 'VENTUS'],
  'g_powers': [300,
               310,
               320,
               330,
               340,
               350,
               360,
               370,
               380,
               390,
               400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550],
  'price': 150},
 {'name': 'Ravenoid',
  'allowed_attributes': ['PYRUS', 'HAOS', 'VENTUS'],
  'g_powers': [300,
               310,
               320,
               330,
               340,
               350,
               360,
               370,
               380,
               390,
               400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550],
  'price': 150},
 {'name': 'Stinglash',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [230,
               240,
               250,
               260,
               270,
               280,
               290,
               300,
               310,
               320,
               330,
               340,
               350,
               360,
               370,
               380,
               390,
               400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480],
  'price': 115},
 {'name': 'Centipoid',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [240,
               250,
               260,
               270,
               280,
               290,
               300,
               310,
               320,
               330,
               340,
               350,
               360,
               370,
               380,
               390,
               400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490],
  'price': 120},
 {'name': 'Gargonoid',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'DARKUS', 'VENTUS'],
  'g_powers': [250,
               260,
               270,
               280,
               290,
               300,
               310,
               320,
               330,
               340,
               350,
               360,
               370,
               380,
               390,
               400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500],
  'price': 125},
 {'name': 'Fear Ripper',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [270,
               280,
               290,
               300,
               310,
               320,
               330,
               340,
               350,
               360,
               370,
               380,
               390,
               400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520],
  'price': 135},
 {'name': 'Siege',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [270,
               280,
               290,
               300,
               310,
               320,
               330,
               340,
               350,
               360,
               370,
               380,
               390,
               400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520],
  'price': 135},
 {'name': 'Monarus',
  'allowed_attributes': ['PYRUS', 'HAOS', 'VENTUS'],
  'g_powers': [300,
               310,
               320,
               330,
               340,
               350,
               360,
               370,
               380,
               390,
               400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550],
  'price': 150},
 {'name': 'Griffon',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [300,
               310,
               320,
               330,
               340,
               350,
               360,
               370,
               380,
               390,
               400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550],
  'price': 150},
 {'name': 'Terrorclaw',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS'],
  'g_powers': [320,
               330,
               340,
               350,
               360,
               370,
               380,
               390,
               400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550,
               560,
               570],
  'price': 160},
 {'name': 'Laserman',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [370,
               380,
               390,
               400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550,
               560,
               570,
               580,
               590,
               600,
               610,
               620],
  'price': 185},
 {'name': 'Reaper',
  'allowed_attributes': ['AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [380,
               390,
               400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550,
               560,
               570,
               580,
               590,
               600,
               610,
               620,
               630],
  'price': 190},
 {'name': 'Leonidas',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550,
               560,
               570,
               580,
               590,
               600,
               610,
               620,
               630,
               640,
               650,
               660,
               670],
  'price': 210},
 {'name': 'Omega Leonidas',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [650,
               660,
               670,
               680,
               690,
               700,
               710,
               720,
               730,
               740,
               750,
               760,
               770,
               780,
               790,
               800,
               810,
               820,
               830,
               840,
               850,
               860,
               870,
               880,
               890,
               900],
  'price': 325},
 {'name': 'Fourtress',
  'allowed_attributes': ['PYRUS'],
  'g_powers': [390,
               400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550,
               560,
               570,
               580,
               590,
               600,
               610,
               620,
               630,
               640],
  'price': 195},
 {'name': 'Dragonoid',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550,
               560,
               570,
               580,
               590,
               600,
               610,
               620,
               630,
               640,
               650],
  'price': 200},
 {'name': 'Delta Dragonoid',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [500,
               510,
               520,
               530,
               540,
               550,
               560,
               570,
               580,
               590,
               600,
               610,
               620,
               630,
               640,
               650,
               660,
               670,
               680,
               690,
               700,
               710,
               720,
               730,
               740,
               750],
  'price': 250},
 {'name': 'Sirenoid',
  'allowed_attributes': ['AQUOS'],
  'g_powers': [390,
               400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550,
               560,
               570,
               580,
               590,
               600,
               610,
               620,
               630,
               640],
  'price': 195},
 {'name': 'Preyas',
  'allowed_attributes': ['AQUOS'],
  'g_powers': [380,
               390,
               400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550,
               560,
               570,
               580,
               590,
               600,
               610,
               620,
               630],
  'price': 190},
 {'name': 'Cycloid',
  'allowed_attributes': ['SUBTERRA'],
  'g_powers': [390,
               400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550,
               560,
               570,
               580,
               590,
               600,
               610,
               620,
               630,
               640],
  'price': 195},
 {'name': 'Gorem',
  'allowed_attributes': ['SUBTERRA'],
  'g_powers': [400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550,
               560,
               570,
               580,
               590,
               600,
               610,
               620,
               630,
               640,
               650],
  'price': 200},
 {'name': 'Hammer Gorem',
  'allowed_attributes': ['SUBTERRA'],
  'g_powers': [500,
               510,
               520,
               530,
               540,
               550,
               560,
               570,
               580,
               590,
               600,
               610,
               620,
               630,
               640,
               650,
               660,
               670,
               680,
               690,
               700,
               710,
               720,
               730,
               740,
               750],
  'price': 250},
 {'name': 'Tentaclear',
  'allowed_attributes': ['HAOS'],
  'g_powers': [390,
               400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550,
               560,
               570,
               580,
               590,
               600,
               610,
               620,
               630,
               640],
  'price': 195},
 {'name': 'Tigrerra',
  'allowed_attributes': ['HAOS'],
  'g_powers': [400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550,
               560,
               570,
               580,
               590,
               600,
               610,
               620,
               630,
               640,
               650],
  'price': 200},
 {'name': 'Blade Tigrerra',
  'allowed_attributes': ['HAOS'],
  'g_powers': [500,
               510,
               520,
               530,
               540,
               550,
               560,
               570,
               580,
               590,
               600,
               610,
               620,
               630,
               640,
               650,
               660,
               670,
               680,
               690,
               700,
               710,
               720,
               730,
               740,
               750],
  'price': 250},
 {'name': 'Hydranoid',
  'allowed_attributes': ['DARKUS'],
  'g_powers': [450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550,
               560,
               570,
               580,
               590,
               600,
               610,
               620,
               630,
               640,
               650,
               660,
               670,
               680,
               690,
               700],
  'price': 225},
 {'name': 'Dual Hydranoid',
  'allowed_attributes': ['DARKUS'],
  'g_powers': [550,
               560,
               570,
               580,
               590,
               600,
               610,
               620,
               630,
               640,
               650,
               660,
               670,
               680,
               690,
               700,
               710,
               720,
               730,
               740,
               750,
               760,
               770,
               780,
               790,
               800],
  'price': 275},
 {'name': 'Vladitor',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550,
               560,
               570,
               580,
               590,
               600,
               610,
               620,
               630,
               640,
               650,
               660,
               670],
  'price': 210},
 {'name': 'Battle Ax Vladitor',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [650,
               660,
               670,
               680,
               690,
               700,
               710,
               720,
               730,
               740,
               750,
               760,
               770,
               780,
               790,
               800,
               810,
               820,
               830,
               840,
               850,
               860,
               870,
               880,
               890,
               900],
  'price': 325},
 {'name': 'Harpus',
  'allowed_attributes': ['VENTUS'],
  'g_powers': [390,
               400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550,
               560,
               570,
               580,
               590,
               600,
               610,
               620,
               630,
               640],
  'price': 195},
 {'name': 'Skyress',
  'allowed_attributes': ['VENTUS'],
  'g_powers': [400,
               410,
               420,
               430,
               440,
               450,
               460,
               470,
               480,
               490,
               500,
               510,
               520,
               530,
               540,
               550,
               560,
               570,
               580,
               590,
               600,
               610,
               620,
               630,
               640,
               650],
  'price': 200},
 {'name': 'Storm Skyress',
  'allowed_attributes': ['VENTUS'],
  'g_powers': [500,
               510,
               520,
               530,
               540,
               550,
               560,
               570,
               580,
               590,
               600,
               610,
               620,
               630,
               640,
               650,
               660,
               670,
               680,
               690,
               700,
               710,
               720,
               730,
               740,
               750],
  'price': 250},
 {'name': 'Angelo/Diablo Preyas',
  'allowed_attributes': ['AQUOS'],
  'g_powers': [450, 460, 470, 480, 490, 500],
  'price': 280},
 {'name': 'Ultimate Dragonoid',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [500, 510, 520, 530, 540, 550],
  'price': 420},
 {'name': 'Neo Dragonoid',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [500, 510, 520, 530, 540, 550],
  'price': 430},
 {'name': 'Cross Dragonoid',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [540, 550, 560, 570, 580],
  'price': 500},
 {'name': 'Helix Dragonoid',
  'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'g_powers': [560, 570, 580, 590, 600],
  'price': 560},
 {'name': 'Master Ingram',
  'allowed_attributes': ['VENTUS'],
  'g_powers': [500, 510, 520, 530, 540],
  'price': 430},
 {'name': 'Knight Percival',
  'allowed_attributes': ['DARKUS'],
  'g_powers': [500, 510, 520, 530, 540],
  'price': 430},
 {'name': 'Minx Elfin',
  'allowed_attributes': ['AQUOS'],
  'g_powers': [500, 510, 520, 530, 540],
  'price': 430},
 {'name': 'Viper Helios',
  'allowed_attributes': ['DARKUS'],
  'g_powers': [500, 510, 520, 530, 540],
  'price': 430},
 {'name': 'Cyborg Helios',
  'allowed_attributes': ['DARKUS'],
  'g_powers': [540, 550, 560, 570, 580],
  'price': 510},
 {'name': 'Rex Vulcan',
  'allowed_attributes': ['SUBTERRA'],
  'g_powers': [500, 510, 520, 530, 540],
  'price': 430}]

RAW_ABILITY_CARDS = [{'name': 'A Hand Up',
  'color': 'RED',
  'timing': 'DURING_ROLL',
  'description': 'If your Bakugan has the lower original G-Power, it gets +100 G-Power this '
                 'battle.',
  'effect_id': 'EXACT_A_HAND_UP',
  'price': 130},
 {'name': 'Brainwash',
  'color': 'RED',
  'timing': 'DURING_ROLL',
  'description': "If the battle is on your opponent's Gate Card, your Bakugan gets +100 G-Power "
                 'this battle.',
  'effect_id': 'ROLL_CHOOSE_BEST',
  'price': 130},
 {'name': 'Clean Slate',
  'color': 'RED',
  'timing': 'DURING_ROLL',
  'description': 'Reset both battling Bakugan to their original G-Powers before other battle '
                 'bonuses this battle.',
  'effect_id': 'EXACT_CLEAN_SLATE',
  'price': 120},
 {'name': 'Colorvoid',
  'color': 'RED',
  'timing': 'DURING_ROLL',
  'description': 'Cancel attribute-based bonus effects for both battling Bakugan this battle.',
  'effect_id': 'EXACT_COLORVOID',
  'price': 120},
 {'name': 'Combo Battle',
  'color': 'RED',
  'timing': 'DURING_ROLL',
  'description': 'If this roll starts a battle, both players add one valid support Bakugan to the '
                 'battle.',
  'effect_id': 'EXACT_COMBO_BATTLE',
  'price': 160},
 {'name': "Alice's Surprise",
  'color': 'BLUE',
  'timing': 'DURING_BATTLE',
  'description': 'If your opponent has more used Ability Cards than you, gain +100 G for Pyrus, '
                 '+80 for Subterra or Haos, and +50 for Aquos, Darkus, or Ventus.',
  'effect_id': 'EXACT_ALICES_SURPRISE',
  'price': 180},
 {'name': 'Big Brawl',
  'color': 'BLUE',
  'timing': 'DURING_BATTLE',
  'description': 'Gain G-Power based on the number of different Attributes among standing Bakugan '
                 'on the field.',
  'effect_id': 'EXACT_BIG_BRAWL',
  'price': 180},
 {'name': 'Brushfire',
  'color': 'BLUE',
  'timing': 'DURING_BATTLE',
  'description': "If the battle is on your opponent's Gate Card, +140 G-Power for Pyrus and +70 "
                 'G-Power for Subterra',
  'effect_id': 'EXACT_BRUSHFIRE',
  'price': 150},
 {'name': 'Power from Darkness',
  'color': 'BLUE',
  'timing': 'DURING_BATTLE',
  'description': "If the battle is on your opponent's Gate Card, +140 G for Darkus and +60 G for "
                 'Haos.',
  'effect_id': 'EXACT_POWER_FROM_DARKNESS',
  'price': 150},
 {'name': 'Aquos',
  'color': 'GREEN',
  'timing': 'FLEXIBLE',
  'description': 'If your battling Bakugan is Aquos, replace it with one of your unused Bakugan at '
                 'the start of the battle.',
  'effect_id': 'EXACT_AQUOS_SWAP',
  'price': 160},
 {'name': 'Attractor',
  'color': 'GREEN',
  'timing': 'FLEXIBLE',
  'description': 'Move one of your standing Bakugan onto the current battle and add it as support '
                 'if legal.',
  'effect_id': 'GREEN_BEST_GATE_MATCH',
  'price': 150},
 {'name': 'Color Swap',
  'color': 'GREEN',
  'timing': 'FLEXIBLE',
  'description': "If your Bakugan has the lower original G-Power, swap the battling Bakugan's "
                 'Attributes for this battle.',
  'effect_id': 'EXACT_COLOR_SWAP',
  'price': 150},
 {'name': 'Doom Card',
  'color': 'GREEN',
  'timing': 'FLEXIBLE',
  'description': 'The losing Bakugan is removed from the rest of the match.',
  'effect_id': 'EXACT_DOOM_CARD',
  'price': 200},
 {'name': 'Earth Shutdown',
  'color': 'GREEN',
  'timing': 'FLEXIBLE',
  'description': 'Your opponent cannot use Green Ability Cards this battle.',
  'effect_id': 'EXACT_EARTH_SHUTDOWN',
  'price': 170},
 {'name': 'Lockdown',
  'color': 'RED',
  'timing': 'DURING_ROLL',
  'description': 'Improve this roll; if it starts a battle, your opponent cannot play a Red '
                 'Ability Card.',
  'effect_id': 'ROLL_PLUS',
  'price': 110},
 {'name': 'Quickfire',
  'color': 'RED',
  'timing': 'DURING_ROLL',
  'description': 'If your Bakugan is Pyrus, improve this roll and gain +50 G if it starts a '
                 'battle.',
  'effect_id': 'ROLL_BATTLE_BONUS',
  'price': 110},
 {'name': 'Level Down',
  'color': 'RED',
  'timing': 'DURING_ROLL',
  'description': "Reduce the opponent's Bakugan by 100 G-Power this battle.",
  'effect_id': 'ROLL_RECOVER',
  'price': 110},
 {'name': 'Fire Judge',
  'color': 'RED',
  'timing': 'DURING_ROLL',
  'description': 'If your Bakugan is Pyrus, gain +120 G-Power this battle.',
  'effect_id': 'ROLL_IGNORE_BAD_MATCH',
  'price': 110},
 {'name': 'Fire Wind',
  'color': 'RED',
  'timing': 'DURING_ROLL',
  'description': 'Gain +80 G for Ventus and +50 G for Pyrus and Darkus this battle.',
  'effect_id': 'ROLL_BATTLE_BONUS',
  'price': 120},
 {'name': 'Do Over',
  'color': 'RED',
  'timing': 'DURING_ROLL',
  'description': 'Restart the current battle with the same Bakugan and Gate Card.',
  'effect_id': 'ROLL_RECOVER',
  'price': 120},
 {'name': 'Legends of Light',
  'color': 'BLUE',
  'timing': 'DURING_BATTLE',
  'description': 'Haos gets +80 G, Subterra and Darkus get +50 G this battle.',
  'effect_id': 'BATTLE_PLUS_120',
  'price': 160},
 {'name': 'Legends of Darkness',
  'color': 'BLUE',
  'timing': 'DURING_BATTLE',
  'description': 'Darkus gets +80 G, Haos and Ventus get +50 G this battle.',
  'effect_id': 'BATTLE_DARKUS_BOOST',
  'price': 160},
 {'name': 'Legends of Wind',
  'color': 'BLUE',
  'timing': 'DURING_BATTLE',
  'description': 'Ventus gets +80 G, Pyrus and Darkus get +50 G this battle.',
  'effect_id': 'BATTLE_PLUS_80',
  'price': 150},
 {'name': 'Legends of Fire',
  'color': 'BLUE',
  'timing': 'DURING_BATTLE',
  'description': 'Pyrus gets +80 G, Aquos and Ventus get +50 G this battle.',
  'effect_id': 'BATTLE_PYRUS_BOOST',
  'price': 150},
 {'name': 'Blue-Green Combine',
  'color': 'BLUE',
  'timing': 'DURING_BATTLE',
  'description': 'Gain +100 G-Power if you have both a Blue and a Green Ability Card in your used '
                 'pile.',
  'effect_id': 'BATTLE_PLUS_120',
  'price': 170},
 {'name': 'Boost All',
  'color': 'BLUE',
  'timing': 'DURING_BATTLE',
  'description': 'All of your standing Bakugan gain +50 G-Power this battle.',
  'effect_id': 'BATTLE_PLUS_60',
  'price': 130},
 {'name': 'Darkus',
  'color': 'GREEN',
  'timing': 'FLEXIBLE',
  'description': 'If your Bakugan is Darkus, gain +120 G-Power this battle.',
  'effect_id': 'GREEN_SABOTAGE_100',
  'price': 150},
 {'name': 'Aquos 2',
  'color': 'GREEN',
  'timing': 'FLEXIBLE',
  'description': 'If your Bakugan is Aquos, gain +120 G-Power this battle.',
  'effect_id': 'GREEN_BEST_GATE_MATCH',
  'price': 140},
 {'name': 'Light Shutdown',
  'color': 'GREEN',
  'timing': 'FLEXIBLE',
  'description': 'Your opponent cannot use Haos-based Ability effects this battle.',
  'effect_id': 'GREEN_BLOCK_ENEMY',
  'price': 140},
 {'name': 'Wind Shutdown',
  'color': 'GREEN',
  'timing': 'FLEXIBLE',
  'description': 'Your opponent cannot use Ventus-based Ability effects this battle.',
  'effect_id': 'GREEN_BLOCK_ENEMY',
  'price': 140},
 {'name': 'Preyas Switch',
  'color': 'GREEN',
  'timing': 'FLEXIBLE',
  'description': "Swap the battling Bakugan's original G-Powers for this battle.",
  'effect_id': 'EXACT_SWAP_ORIGINAL_G',
  'price': 160},
 {'name': 'Help From Friends',
  'color': 'GREEN',
  'timing': 'FLEXIBLE',
  'description': 'Return one of your used Ability Cards to your unused pile.',
  'effect_id': 'EXACT_RETURN_USED_ABILITY',
  'price': 150},
 {'name': 'Bright Light',
  'color': 'BLUE',
  'timing': 'DURING_BATTLE',
  'description': 'Your Bakugan gets double Gate Card bonus this battle.',
  'effect_id': 'EXACT_DOUBLE_GATE_BONUS',
  'price': 150},
 {'name': 'Dragonoid Charge',
  'color': 'BLUE',
  'timing': 'DURING_BATTLE',
  'description': 'If your Bakugan is a Dragonoid, it gets double Gate Card bonus this battle.',
  'effect_id': 'EXACT_DRAGONOID_DOUBLE_GATE',
  'price': 160},
 {'name': 'Bee Striker',
  'color': 'BLUE',
  'timing': 'DURING_BATTLE',
  'description': 'Gain 50 G for each Gate Card you have won this match.',
  'effect_id': 'EXACT_GATE_WON_SCALING',
  'price': 150},
 {'name': 'Dark Growth',
  'color': 'BLUE',
  'timing': 'DURING_BATTLE',
  'description': 'Gain 40 G for each Ability Card in your used pile.',
  'effect_id': 'EXACT_USED_ABILITY_SCALING',
  'price': 150}]

RAW_GATE_CARDS = [{'name': 'Serpenoid',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 180, 'AQUOS': 60, 'SUBTERRA': 90, 'HAOS': 140, 'DARKUS': 130, 'VENTUS': 50},
  'description': 'Serpenoid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Juggernoid',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 80, 'AQUOS': 160, 'SUBTERRA': 70, 'HAOS': 100, 'DARKUS': 70, 'VENTUS': 40},
  'description': 'Juggernoid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Robotallion',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 160, 'AQUOS': 110, 'SUBTERRA': 90, 'HAOS': 120, 'DARKUS': 90, 'VENTUS': 40},
  'description': 'Robotallion gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Saurus',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 100, 'AQUOS': 50, 'SUBTERRA': 180, 'HAOS': 100, 'DARKUS': 50, 'VENTUS': 80},
  'description': 'Saurus gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Falconeer',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 80, 'AQUOS': 100, 'SUBTERRA': 80, 'HAOS': 70, 'DARKUS': 80, 'VENTUS': 160},
  'description': 'Falconeer gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Warius',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 160, 'AQUOS': 100, 'SUBTERRA': 70, 'HAOS': 70, 'DARKUS': 90, 'VENTUS': 70},
  'description': 'Warius gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Manion',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 60, 'AQUOS': 50, 'SUBTERRA': 150, 'HAOS': 70, 'DARKUS': 10, 'VENTUS': 130},
  'description': 'Manion gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Ravenoid',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 90, 'AQUOS': 60, 'SUBTERRA': 70, 'HAOS': 130, 'DARKUS': 30, 'VENTUS': 180},
  'description': 'Ravenoid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Stinglash',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 80, 'AQUOS': 90, 'SUBTERRA': 130, 'HAOS': 50, 'DARKUS': 150, 'VENTUS': 50},
  'description': 'Stinglash gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Centipoid',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 70, 'AQUOS': 40, 'SUBTERRA': 140, 'HAOS': 130, 'DARKUS': 160, 'VENTUS': 100},
  'description': 'Centipoid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Gargonoid',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 160, 'AQUOS': 110, 'SUBTERRA': 70, 'HAOS': 40, 'DARKUS': 70, 'VENTUS': 160},
  'description': 'Gargonoid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Fear Ripper',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 90, 'AQUOS': 110, 'SUBTERRA': 90, 'HAOS': 170, 'DARKUS': 70, 'VENTUS': 80},
  'description': 'Fear Ripper gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Siege',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 70, 'AQUOS': 170, 'SUBTERRA': 60, 'HAOS': 100, 'DARKUS': 60, 'VENTUS': 50},
  'description': 'Siege gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Monarus',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 30, 'AQUOS': 50, 'SUBTERRA': 70, 'HAOS': 80, 'DARKUS': 20, 'VENTUS': 180},
  'description': 'Monarus gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Griffon',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 140, 'AQUOS': 120, 'SUBTERRA': 100, 'HAOS': 130, 'DARKUS': 50, 'VENTUS': 80},
  'description': 'Griffon gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Terrorclaw',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 40, 'AQUOS': 180, 'SUBTERRA': 90, 'HAOS': 40, 'DARKUS': 40, 'VENTUS': 80},
  'description': 'Terrorclaw gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Laserman',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 80, 'AQUOS': 100, 'SUBTERRA': 130, 'HAOS': 90, 'DARKUS': 180, 'VENTUS': 130},
  'description': 'Laserman gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Leonidas',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 100, 'AQUOS': 100, 'SUBTERRA': 100, 'HAOS': 100, 'DARKUS': 100, 'VENTUS': 100},
  'description': 'Leonidas gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Omega Leonidas',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 200, 'AQUOS': 200, 'SUBTERRA': 200, 'HAOS': 200, 'DARKUS': 200, 'VENTUS': 200},
  'description': 'Omega Leonidas gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Vladitor',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 20, 'AQUOS': 20, 'SUBTERRA': 20, 'HAOS': 20, 'DARKUS': 150, 'VENTUS': 20},
  'description': 'Vladitor gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Battle Ax Vladitor',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 10, 'AQUOS': 10, 'SUBTERRA': 10, 'HAOS': 10, 'DARKUS': 200, 'VENTUS': 10},
  'description': 'Battle Ax Vladitor gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Dragonoid',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 150, 'AQUOS': 50, 'SUBTERRA': 70, 'HAOS': 30, 'DARKUS': 50, 'VENTUS': 40},
  'description': 'Dragonoid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Delta Dragonoid II',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 200, 'AQUOS': 100, 'SUBTERRA': 150, 'HAOS': 50, 'DARKUS': 100, 'VENTUS': 50},
  'description': 'Delta Dragonoid II gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Fortress',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 180, 'AQUOS': 110, 'SUBTERRA': 170, 'HAOS': 130, 'DARKUS': 100, 'VENTUS': 140},
  'description': 'Fortress gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Preyas',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 10, 'AQUOS': 150, 'SUBTERRA': 150, 'HAOS': 20, 'DARKUS': 150, 'VENTUS': 10},
  'description': 'Preyas gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': "Preyas's",
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 100, 'AQUOS': 200, 'SUBTERRA': 180, 'HAOS': 50, 'DARKUS': 180, 'VENTUS': 10},
  'description': 'Preyas II gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Sirenoid',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 150, 'AQUOS': 180, 'SUBTERRA': 110, 'HAOS': 120, 'DARKUS': 70, 'VENTUS': 130},
  'description': 'Sirenoid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Gorem',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 80, 'AQUOS': 10, 'SUBTERRA': 150, 'HAOS': 20, 'DARKUS': 30, 'VENTUS': 50},
  'description': 'Gorem gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Hammer Gorem',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 150, 'AQUOS': 90, 'SUBTERRA': 200, 'HAOS': 120, 'DARKUS': 70, 'VENTUS': 130},
  'description': 'Hammer Gorem gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Cycloid',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 150, 'AQUOS': 120, 'SUBTERRA': 180, 'HAOS': 120, 'DARKUS': 100, 'VENTUS': 60},
  'description': 'Cycloid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Tigrerra',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 50, 'AQUOS': 50, 'SUBTERRA': 90, 'HAOS': 150, 'DARKUS': 20, 'VENTUS': 10},
  'description': 'Tigrerra gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Blade Tigrerra',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 50, 'AQUOS': 40, 'SUBTERRA': 90, 'HAOS': 200, 'DARKUS': 150, 'VENTUS': 60},
  'description': 'Blade Tigrerra gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Tentaclear',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 120, 'AQUOS': 100, 'SUBTERRA': 150, 'HAOS': 180, 'DARKUS': 100, 'VENTUS': 50},
  'description': 'Tentaclear gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Hydranoid',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 20, 'AQUOS': 40, 'SUBTERRA': 10, 'HAOS': 10, 'DARKUS': 150, 'VENTUS': 50},
  'description': 'Hydranoid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Dual Hydranoid',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 70, 'AQUOS': 90, 'SUBTERRA': 130, 'HAOS': 130, 'DARKUS': 200, 'VENTUS': 60},
  'description': 'Dual Hydranoid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Reaper',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 100, 'AQUOS': 50, 'SUBTERRA': 150, 'HAOS': 70, 'DARKUS': 200, 'VENTUS': 140},
  'description': 'Reaper gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Skyress',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 20, 'AQUOS': 50, 'SUBTERRA': 50, 'HAOS': 50, 'DARKUS': 70, 'VENTUS': 150},
  'description': 'Skyress gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Storm Skyress',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 150, 'AQUOS': 50, 'SUBTERRA': 60, 'HAOS': 90, 'DARKUS': 40, 'VENTUS': 200},
  'description': 'Storm Skyress gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Harpus',
  'gate_type': 'GOLD',
  'bonuses': {'PYRUS': 120, 'AQUOS': 140, 'SUBTERRA': 100, 'HAOS': 110, 'DARKUS': 90, 'VENTUS': 180},
  'description': 'Harpus gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'price': 130},
 {'name': 'Fire Pit',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 140, 'AQUOS': 120, 'SUBTERRA': 80, 'HAOS': 20, 'DARKUS': 20, 'VENTUS': 60},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Muddy Ground',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 20, 'AQUOS': 60, 'SUBTERRA': 140, 'HAOS': 120, 'DARKUS': 80, 'VENTUS': 20},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Light-Burst',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 50, 'AQUOS': 50, 'SUBTERRA': 90, 'HAOS': 200, 'DARKUS': 170, 'VENTUS': 110},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Tsunami',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 20, 'AQUOS': 170, 'SUBTERRA': 110, 'HAOS': 80, 'DARKUS': 110, 'VENTUS': 50},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Dusk',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 80, 'AQUOS': 20, 'SUBTERRA': 20, 'HAOS': 60, 'DARKUS': 140, 'VENTUS': 120},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'High Energy',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 110, 'AQUOS': 120, 'SUBTERRA': 120, 'HAOS': 110, 'DARKUS': 120, 'VENTUS': 120},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Whirlpool',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 90, 'AQUOS': 200, 'SUBTERRA': 170, 'HAOS': 110, 'DARKUS': 50, 'VENTUS': 50},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Aquos Vortex',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 60, 'AQUOS': 150, 'SUBTERRA': 120, 'HAOS': 50, 'DARKUS': 20, 'VENTUS': 20},
  'description': 'None',
  'effect_id': 'GATE_AQUOS_FOCUS',
  'price': 110},
 {'name': 'Heavy Surf',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 60, 'AQUOS': 140, 'SUBTERRA': 120, 'HAOS': 80, 'DARKUS': 20, 'VENTUS': 40},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Elevated Field',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 90, 'AQUOS': 110, 'SUBTERRA': 100, 'HAOS': 90, 'DARKUS': 110, 'VENTUS': 100},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Earthen Mound',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 50, 'AQUOS': 90, 'SUBTERRA': 200, 'HAOS': 170, 'DARKUS': 110, 'VENTUS': 50},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Sand Storm',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 110, 'AQUOS': 80, 'SUBTERRA': 110, 'HAOS': 50, 'DARKUS': 20, 'VENTUS': 170},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'The Cliffs',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 120, 'AQUOS': 100, 'SUBTERRA': 150, 'HAOS': 50, 'DARKUS': 100, 'VENTUS': 50},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Black Hole',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 120, 'AQUOS': 100, 'SUBTERRA': 150, 'HAOS': 50, 'DARKUS': 100, 'VENTUS': 50},
  'description': 'None',
  'effect_id': 'GATE_LOW_G_ADVANTAGE',
  'price': 110},
 {'name': 'Tornado Alley',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 170, 'AQUOS': 110, 'SUBTERRA': 50, 'HAOS': 50, 'DARKUS': 90, 'VENTUS': 180},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Force Wind',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 120, 'AQUOS': 80, 'SUBTERRA': 20, 'HAOS': 40, 'DARKUS': 60, 'VENTUS': 140},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'The Spires',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 50, 'AQUOS': 40, 'SUBTERRA': 40, 'HAOS': 110, 'DARKUS': 70, 'VENTUS': 150},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Wind Farm',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 50, 'AQUOS': 20, 'SUBTERRA': 50, 'HAOS': 60, 'DARKUS': 20, 'VENTUS': 70},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Blue Sky',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 50, 'AQUOS': 40, 'SUBTERRA': 40, 'HAOS': 110, 'DARKUS': 70, 'VENTUS': 150},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Vacuum',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 50, 'AQUOS': 20, 'SUBTERRA': 50, 'HAOS': 60, 'DARKUS': 20, 'VENTUS': 70},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Volcanic Lake',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 200, 'AQUOS': 170, 'SUBTERRA': 110, 'HAOS': 50, 'DARKUS': 50, 'VENTUS': 90},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Powder Keg',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 140, 'AQUOS': 120, 'SUBTERRA': 80, 'HAOS': 20, 'DARKUS': 40, 'VENTUS': 60},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Earthen Wave',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 140, 'AQUOS': 120, 'SUBTERRA': 80, 'HAOS': 20, 'DARKUS': 40, 'VENTUS': 60},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Low Energy',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 50, 'AQUOS': 60, 'SUBTERRA': 20, 'HAOS': 70, 'DARKUS': 50, 'VENTUS': 20},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Sunrise',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 20, 'AQUOS': 20, 'SUBTERRA': 60, 'HAOS': 140, 'DARKUS': 120, 'VENTUS': 80},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Spitting Fire',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 60, 'AQUOS': 150, 'SUBTERRA': 120, 'HAOS': 50, 'DARKUS': 20, 'VENTUS': 20},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Sun Spot',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 60, 'AQUOS': 140, 'SUBTERRA': 120, 'HAOS': 80, 'DARKUS': 20, 'VENTUS': 40},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Haunted Night',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 110, 'AQUOS': 50, 'SUBTERRA': 50, 'HAOS': 90, 'DARKUS': 200, 'VENTUS': 170},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Pit Dweller',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 100, 'AQUOS': 50, 'SUBTERRA': 120, 'HAOS': 100, 'DARKUS': 150, 'VENTUS': 50},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Nightmare',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 80, 'AQUOS': 70, 'SUBTERRA': 20, 'HAOS': 120, 'DARKUS': 170, 'VENTUS': 120},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Fields Of Lava',
  'gate_type': 'SILVER',
  'bonuses': {'PYRUS': 80, 'AQUOS': 70, 'SUBTERRA': 20, 'HAOS': 120, 'DARKUS': 170, 'VENTUS': 120},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 110},
 {'name': 'Lockdown',
  'gate_type': 'BRONZE',
  'bonuses': {'PYRUS': 110, 'AQUOS': 100, 'SUBTERRA': 80, 'HAOS': 70, 'DARKUS': 50, 'VENTUS': 40},
  'description': 'All G-Power boosts from Ability Cards are doubled',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 120},
 {'name': 'G-Power Exchange',
  'gate_type': 'BRONZE',
  'bonuses': {'PYRUS': 60, 'AQUOS': 30, 'SUBTERRA': 50, 'HAOS': 20, 'DARKUS': 20, 'VENTUS': 40},
  'description': "Each Bakugan's original G-Power is swapped",
  'effect_id': 'GATE_EXACT_NONE',
  'price': 120},
 {'name': 'Mega Warrior',
  'gate_type': 'BRONZE',
  'bonuses': {'PYRUS': 100, 'AQUOS': 40, 'SUBTERRA': 50, 'HAOS': 110, 'DARKUS': 150, 'VENTUS': 50},
  'description': '+100 G-Power for each Gate Card each side has won',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 120},
 {'name': 'Stand Off',
  'gate_type': 'BRONZE',
  'bonuses': {'PYRUS': 140, 'AQUOS': 80, 'SUBTERRA': 50, 'HAOS': 80, 'DARKUS': 60, 'VENTUS': 20},
  'description': 'Neither side can play Ability Cards',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 120},
 {'name': 'Stand Your Ground',
  'gate_type': 'BRONZE',
  'bonuses': {'PYRUS': 20, 'AQUOS': 80, 'SUBTERRA': 140, 'HAOS': 50, 'DARKUS': 60, 'VENTUS': 110},
  'description': 'Both players get all used Ability Cards back',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 120},
 {'name': 'Trick Jump',
  'gate_type': 'BRONZE',
  'bonuses': {'PYRUS': 110, 'AQUOS': 80, 'SUBTERRA': 60, 'HAOS': 90, 'DARKUS': 120, 'VENTUS': 140},
  'description': '+100 G-Power for each Ability Card each side has used',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 120},
 {'name': 'Overtake',
  'gate_type': 'BRONZE',
  'bonuses': {'PYRUS': 80, 'AQUOS': 90, 'SUBTERRA': 50, 'HAOS': 50, 'DARKUS': 60, 'VENTUS': 80},
  'description': 'The Bakugan with the lowest original G-Power has its original G-Power doubled',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 120},
 {'name': 'Reflexes',
  'gate_type': 'BRONZE',
  'bonuses': {'PYRUS': 110, 'AQUOS': 170, 'SUBTERRA': 110, 'HAOS': 140, 'DARKUS': 170, 'VENTUS': 140},
  'description': 'The Bakugan with the lowest original G-Power has its original G-Power doubled',
  'effect_id': 'GATE_EXACT_NONE',
  'price': 120},
 {'name': 'Power Siphon',
  'gate_type': 'BRONZE',
  'bonuses': {'PYRUS': 110, 'AQUOS': 100, 'SUBTERRA': 80, 'HAOS': 70, 'DARKUS': 50, 'VENTUS': 40},
  'description': "Each Bakugan's original G-Power is swapped if one of the combatants is Aquos",
  'effect_id': 'GATE_EXACT_NONE',
  'price': 120}]
