"""Ability card data."""
import re
PRICE_MODIFIER = 1.0
# Economy tuning knobs
ABILITY_BASE_MULTIPLIER = 0.85
ABILITY_NAMED_GREEN_BASE = 95
ABILITY_NAMED_GREEN_PER_100G = 28
ABILITY_PREMIUM_BY_NAME = {
    'Combo Battle': 26,
    'Blue-Green Combine': 20,
    'Help From Friends': 20,
    'Doom Card': 24,
    'Bright Light': 18,
    'Dark Growth': 12,
    'Bee Striker': 12,
    'Carousel Tier 2': 18,
    'Carousel Tier 3': 40,
    "Alice's Surprise": 14,
    'Big Brawl': 12,
    'Attractor': 10,
    'Color Swap': 8,
    'Preyas Switch': 8,
    'Boost All': 8,
}
ABILITY_DISCOUNT_BY_NAME = {
    'Colorvoid': 10,
    'Quickfire': 8,
    'Fire Judge': 8,
}

def _round_price(value):
    return int(round(float(value) / 5.0) * 5)


def _scaled_price(value):
    return max(1, _round_price(float(value) * PRICE_MODIFIER))


def _named_green_amount(card):
    if not str(card.get('name', '')).endswith('Power Strike'):
        return None
    actions = ((card.get('custom_effect') or {}).get('actions') or [])
    for action in actions:
        if action.get('type') == 'add_g':
            return int(action.get('amount', 0))
    match = re.search(r'NAMED_GREEN_(\d+)', str(card.get('effect_id', '')))
    return int(match.group(1)) if match else None


def _priced_ability(card):
    named_green_amount = _named_green_amount(card)
    if named_green_amount is not None:
        price = ABILITY_NAMED_GREEN_BASE + (named_green_amount / 100.0) * ABILITY_NAMED_GREEN_PER_100G
        if named_green_amount >= 400:
            price += 8
        elif named_green_amount >= 300:
            price += 4
        return _scaled_price(price)
    price = float(card.get('price', 0)) * ABILITY_BASE_MULTIPLIER
    price += ABILITY_PREMIUM_BY_NAME.get(card.get('name', ''), 0)
    price -= ABILITY_DISCOUNT_BY_NAME.get(card.get('name', ''), 0)
    return _scaled_price(price)


RAW_ABILITY_CARDS = [
    
    {'color': 'RED',
  'description': 'If your Bakugan has the lower original G-Power, it gets +100 G-Power this battle.',
  'effect_id': 'EXACT_A_HAND_UP',
  'name': 'A Hand Up',
  'price': 145,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [{'type': 'self_original_g_lower'}],
                    'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': "If the battle is on your opponent's Gate Card, your Bakugan gets +100 G-Power this battle.",
  'effect_id': 'ROLL_CHOOSE_BEST',
  'name': 'Brainwash',
  'price': 130,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [{'type': 'battle_on_opponent_gate'}],
                    'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': 'Reset both battling Bakugan to their original G-Powers before other battle bonuses this battle.',
  'effect_id': 'EXACT_CLEAN_SLATE',
  'name': 'Clean Slate',
  'price': 140,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'reset_both_to_original_g'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': 'Cancel attribute-based bonus effects for both battling Bakugan this battle.',
  'effect_id': 'EXACT_COLORVOID',
  'name': 'Colorvoid',
  'price': 120,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'block_attribute_effects', 'target': 'both'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': 'If this roll starts a battle, both players add one valid support Bakugan to the battle.',
  'effect_id': 'EXACT_COMBO_BATTLE',
  'name': 'Combo Battle',
  'price': 160,
  'timing': 'DURING_ROLL',
  'custom_effect': {'timing': 'DURING_ROLL',
                    'conditions': [],
                    'actions': [{'type': 'enable_combo_battle'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'If your opponent has more used Ability Cards than you, gain +100 G for Pyrus, +80 for Subterra or '
                 'Haos, and +50 for Aquos, Darkus, or Ventus.',
  'effect_id': 'EXACT_ALICES_SURPRISE',
  'name': "Alice's Surprise",
  'price': 160,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [{'type': 'opponent_used_more_abilities'}],
                    'actions': [{'type': 'add_g_by_attribute_map',
                                 'target': 'self',
                                 'map': {'PYRUS': 100,
                                         'SUBTERRA': 80,
                                         'HAOS': 80,
                                         'AQUOS': 50,
                                         'DARKUS': 50,
                                         'VENTUS': 50}}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'Gain G-Power based on the number of different Attributes among standing Bakugan on the field.',
  'effect_id': 'EXACT_BIG_BRAWL',
  'name': 'Big Brawl',
  'price': 160,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_by_distinct_field_attributes', 'target': 'self', 'scale': 40}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': "If the battle is on your opponent's Gate Card, +140 G-Power for Pyrus and +70 G-Power for Subterra",
  'effect_id': 'EXACT_BRUSHFIRE',
  'name': 'Brushfire',
  'price': 160,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [{'type': 'battle_on_opponent_gate'}],
                    'actions': [{'type': 'add_g_by_attribute_map',
                                 'target': 'self',
                                 'map': {'PYRUS': 140, 'SUBTERRA': 70}}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': "If the battle is on your opponent's Gate Card, +140 G for Darkus and +60 G for Haos.",
  'effect_id': 'EXACT_POWER_FROM_DARKNESS',
  'name': 'Power from Darkness',
  'price': 160,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [{'type': 'battle_on_opponent_gate'}],
                    'actions': [{'type': 'add_g_by_attribute_map',
                                 'target': 'self',
                                 'map': {'DARKUS': 140, 'HAOS': 60}}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'If your battling Bakugan is Aquos, replace it with one of your unused Bakugan at the start of the '
                 'battle.',
  'effect_id': 'EXACT_AQUOS_SWAP',
  'name': 'Aquos',
  'price': 160,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [{'type': 'self_attribute_is', 'value': 'AQUOS'}],
                    'actions': [{'type': 'replace_with_unused_bakugan'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'Move one of your other standing Bakugan into the battle as support if legal.',
  'effect_id': 'EXACT_ATTRACTOR',
  'name': 'Attractor',
  'price': 150,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [],
                    'actions': [{'type': 'summon_support_bakugan'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': "If your Bakugan has the lower original G-Power, swap the battling Bakugan's Attributes for this "
                 'battle.',
  'effect_id': 'EXACT_COLOR_SWAP',
  'name': 'Color Swap',
  'price': 150,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [{'type': 'self_original_g_lower'}],
                    'actions': [{'type': 'swap_attributes'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'The losing Bakugan is removed from the rest of the match.',
  'effect_id': 'EXACT_DOOM_CARD',
  'name': 'Doom Card',
  'price': 170,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE', 'conditions': [], 'actions': [{'type': 'doom_loser'}], 'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'Your opponent cannot use Green Ability Cards this battle.',
  'effect_id': 'EXACT_EARTH_SHUTDOWN',
  'name': 'Earth Shutdown',
  'price': 140,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [],
                    'actions': [{'type': 'block_color', 'target': 'opponent', 'color': 'GREEN'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': 'Improve this roll; if it starts a battle, your opponent cannot play Red Ability Cards in that '
                 'battle.',
  'effect_id': 'EXACT_LOCKDOWN',
  'name': 'Lockdown',
  'price': 140,
  'timing': 'DURING_ROLL',
  'custom_effect': {'timing': 'DURING_ROLL',
                    'conditions': [],
                    'actions': [{'type': 'improve_roll', 'amount': 0.12},
                                {'type': 'block_color_if_battle_starts', 'target': 'opponent', 'color': 'RED'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': 'If your Bakugan is Pyrus, improve this roll and gain +50 G if it starts a battle.',
  'effect_id': 'ROLL_BATTLE_BONUS',
  'name': 'Quickfire',
  'price': 125,
  'timing': 'DURING_ROLL',
  'custom_effect': {'timing': 'DURING_ROLL',
                    'conditions': [{'type': 'self_attribute_is', 'value': 'PYRUS'}],
                    'actions': [{'type': 'improve_roll', 'amount': 0.06},
                                {'type': 'add_g_on_battle_start', 'target': 'self', 'amount': 50}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': "If your opponent's Bakugan has the higher original G-Power, it loses 100 G-Power this battle.",
  'effect_id': 'EXACT_LEVEL_DOWN',
  'name': 'Level Down',
  'price': 135,
  'timing': 'DURING_ROLL',
  'custom_effect': {'timing': 'DURING_ROLL',
                    'conditions': [],
                    'actions': [{'type': 'pending_high_original_loses_g', 'amount': 100}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': 'If your Bakugan is Pyrus, gain +120 G-Power this battle.',
  'effect_id': 'EXACT_FIRE_JUDGE',
  'name': 'Fire Judge',
  'price': 130,
  'timing': 'DURING_ROLL',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [{'type': 'self_attribute_is', 'value': 'PYRUS'}],
                    'actions': [{'type': 'add_g_on_battle_start', 'target': 'self', 'amount': 120}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': 'Gain +80 G for Ventus and +50 G for Pyrus and Darkus this battle.',
  'effect_id': 'ROLL_BATTLE_BONUS',
  'name': 'Fire Wind',
  'price': 135,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_by_attribute_map',
                                 'target': 'self',
                                 'map': {'VENTUS': 80, 'PYRUS': 50, 'DARKUS': 50}}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': 'If this roll starts a battle, restart the battle and cancel other pending roll-based pre-battle '
                 'effects.',
  'effect_id': 'EXACT_DO_OVER',
  'name': 'Do Over',
  'price': 135,
  'timing': 'DURING_ROLL',
  'custom_effect': {'timing': 'DURING_ROLL',
                    'conditions': [],
                    'actions': [{'type': 'pending_do_over'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Haos gets +80 G-Power; Subterra and Darkus get +50 G-Power this battle.',
  'effect_id': 'EXACT_LEGENDS_OF_LIGHT',
  'name': 'Legends of Light',
  'price': 160,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_by_attribute_map',
                                 'target': 'self',
                                 'map': {'HAOS': 80, 'SUBTERRA': 50, 'DARKUS': 50}}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Darkus gets +80 G, Haos and Ventus get +50 G this battle.',
  'effect_id': 'BATTLE_DARKUS_BOOST',
  'name': 'Legends of Darkness',
  'price': 145,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_by_attribute_map',
                                 'target': 'self',
                                 'map': {'DARKUS': 80, 'HAOS': 50, 'VENTUS': 50}}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Ventus gets +80 G-Power; Pyrus and Darkus get +50 G-Power this battle.',
  'effect_id': 'EXACT_LEGENDS_OF_WIND',
  'name': 'Legends of Wind',
  'price': 160,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_by_attribute_map',
                                 'target': 'self',
                                 'map': {'VENTUS': 80, 'PYRUS': 50, 'DARKUS': 50}}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Pyrus gets +80 G, Aquos and Ventus get +50 G this battle.',
  'effect_id': 'BATTLE_PYRUS_BOOST',
  'name': 'Legends of Fire',
  'price': 150,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_by_attribute_map',
                                 'target': 'self',
                                 'map': {'PYRUS': 80, 'AQUOS': 50, 'VENTUS': 50}}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Gain +100 G-Power if you have both a Blue and a Green Ability Card in your used pile.',
  'effect_id': 'EXACT_BLUE_GREEN_COMBINE',
  'name': 'Blue-Green Combine',
  'price': 170,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [{'type': 'used_colors_include', 'value': ['BLUE', 'GREEN']}],
                    'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'All of your standing Bakugan gain +50 G-Power this battle.',
  'effect_id': 'EXACT_BOOST_ALL',
  'name': 'Boost All',
  'price': 130,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_to_all_friendly_standing', 'amount': 50}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'If your Bakugan is Darkus, gain +120 G-Power this battle.',
  'effect_id': 'EXACT_DARKUS_ONLY',
  'name': 'Darkus',
  'price': 150,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [{'type': 'self_attribute_is', 'value': 'DARKUS'}],
                    'actions': [{'type': 'add_g', 'target': 'self', 'amount': 120}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'If your Bakugan is Aquos, gain +120 G-Power this battle.',
  'effect_id': 'EXACT_AQUOS_ONLY',
  'name': 'Aquos 2',
  'price': 140,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [{'type': 'self_attribute_is', 'value': 'AQUOS'}],
                    'actions': [{'type': 'add_g', 'target': 'self', 'amount': 120}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'Your opponent cannot use Haos-based Ability effects this battle.',
  'effect_id': 'GREEN_BLOCK_ENEMY',
  'name': 'Light Shutdown',
  'price': 140,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [],
                    'actions': [{'type': 'block_attribute_effects_for_attribute',
                                 'target': 'opponent',
                                 'attribute': 'HAOS'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'Your opponent cannot use Ventus-based Ability effects this battle.',
  'effect_id': 'GREEN_BLOCK_ENEMY',
  'name': 'Wind Shutdown',
  'price': 140,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [],
                    'actions': [{'type': 'block_attribute_effects_for_attribute',
                                 'target': 'opponent',
                                 'attribute': 'VENTUS'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': "Swap the battling Bakugan's original G-Powers for this battle.",
  'effect_id': 'EXACT_SWAP_ORIGINAL_G',
  'name': 'Preyas Switch',
  'price': 140,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [],
                    'actions': [{'type': 'swap_original_g'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'Return one of your used Ability Cards to your unused pile.',
  'effect_id': 'EXACT_RETURN_USED_ABILITY',
  'name': 'Help From Friends',
  'price': 160,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [],
                    'actions': [{'type': 'return_one_used_ability'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Your Bakugan gets double Gate Card bonus this battle.',
  'effect_id': 'EXACT_DOUBLE_GATE_BONUS',
  'name': 'Bright Light',
  'price': 150,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Gain 50 G for each Gate Card you have won this match.',
  'effect_id': 'EXACT_GATE_WON_SCALING',
  'name': 'Bee Striker',
  'price': 150,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_by_gates_won', 'target': 'self', 'scale': 50}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Gain 40 G for each Ability Card in your used pile.',
  'effect_id': 'EXACT_USED_ABILITY_SCALING',
  'name': 'Dark Growth',
  'price': 150,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_by_used_abilities', 'target': 'self', 'scale': 40}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Gain a random G-Power bonus from 0 to 100 this battle.',
  'effect_id': 'EXACT_CAROUSEL_T1',
  'name': 'Carousel Tier 1',
  'price': 120,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_random_g', 'target': 'self', 'min': 0, 'max': 100}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Gain a random G-Power bonus from 0 to 250 this battle.',
  'effect_id': 'EXACT_CAROUSEL_T2',
  'name': 'Carousel Tier 2',
  'price': 150,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_random_g', 'target': 'self', 'min': 0, 'max': 250}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Gain a random G-Power bonus from 0 to 400 this battle.',
  'effect_id': 'EXACT_CAROUSEL_T3',
  'name': 'Carousel Tier 3',
  'price': 200,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_random_g', 'target': 'self', 'min': 0, 'max': 400}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''}]

RAW_ABILITY_CARDS += [
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Serpenoid, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Serpenoid Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'serpenoid'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Juggernoid, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Juggernoid Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'juggernoid'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Robotallion, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Robotallion Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'robotallion'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Saurus, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Saurus Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'saurus'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Falconeer, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Falconeer Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'falconeer'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Manion, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Manion Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'manion'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Ravenoid, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Ravenoid Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'ravenoid'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Stinglash, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Stinglash Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'stinglash'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Centipoid, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Centipoid Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'centipoid'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Gargonoid, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Gargonoid Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'gargonoid'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Fear Ripper, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Fear Ripper Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'fear ripper'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Siege, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Siege Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'siege'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Monarus, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Monarus Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'monarus'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Griffon, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Griffon Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'griffon'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Terrorclaw, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Terrorclaw Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'terrorclaw'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Laserman, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Laserman Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'laserman'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Reaper, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Reaper Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'reaper'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Leonidas, gain +200 G-Power this battle.', 'effect_id': 'NAMED_GREEN_200', 'name': 'Leonidas Power Strike', 'price': 170, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'leonidas'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 200}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Omega Leonidas, gain +400 G-Power this battle.', 'effect_id': 'NAMED_GREEN_400', 'name': 'Omega Leonidas Power Strike', 'price': 240, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'omega leonidas'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 400}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Fourtress, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Fourtress Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'fourtress'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Dragonoid, gain +200 G-Power this battle.', 'effect_id': 'NAMED_GREEN_200', 'name': 'Dragonoid Power Strike', 'price': 170, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'dragonoid'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 200}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Delta Dragonoid II, gain +400 G-Power this battle.', 'effect_id': 'NAMED_GREEN_400', 'name': 'Delta Dragonoid II Power Strike', 'price': 240, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'delta dragonoid ii'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 400}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Sirenoid, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Sirenoid Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'sirenoid'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Preyas, gain +200 G-Power this battle.', 'effect_id': 'NAMED_GREEN_200', 'name': 'Preyas Power Strike', 'price': 170, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'preyas'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 200}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Cycloid, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Cycloid Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'cycloid'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Gorem, gain +200 G-Power this battle.', 'effect_id': 'NAMED_GREEN_200', 'name': 'Gorem Power Strike', 'price': 170, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'gorem'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 200}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Hammer Gorem, gain +400 G-Power this battle.', 'effect_id': 'NAMED_GREEN_400', 'name': 'Hammer Gorem Power Strike', 'price': 240, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'hammer gorem'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 400}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Tentaclear, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Tentaclear Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'tentaclear'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Tigrerra, gain +200 G-Power this battle.', 'effect_id': 'NAMED_GREEN_200', 'name': 'Tigrerra Power Strike', 'price': 170, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'tigrerra'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 200}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Blade Tigrerra, gain +400 G-Power this battle.', 'effect_id': 'NAMED_GREEN_400', 'name': 'Blade Tigrerra Power Strike', 'price': 240, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'blade tigrerra'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 400}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Hydranoid, gain +200 G-Power this battle.', 'effect_id': 'NAMED_GREEN_200', 'name': 'Hydranoid Power Strike', 'price': 170, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'hydranoid'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 200}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Dual Hydranoid, gain +400 G-Power this battle.', 'effect_id': 'NAMED_GREEN_400', 'name': 'Dual Hydranoid Power Strike', 'price': 240, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'dual hydranoid'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 400}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Vladitor, gain +200 G-Power this battle.', 'effect_id': 'NAMED_GREEN_200', 'name': 'Vladitor Power Strike', 'price': 170, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'vladitor'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 200}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Battle Ax Vladitor, gain +400 G-Power this battle.', 'effect_id': 'NAMED_GREEN_400', 'name': 'Battle Ax Vladitor Power Strike', 'price': 240, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'battle ax vladitor'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 400}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Harpus, gain +100 G-Power this battle.', 'effect_id': 'NAMED_GREEN_100', 'name': 'Harpus Power Strike', 'price': 120, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'harpus'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Skyress, gain +200 G-Power this battle.', 'effect_id': 'NAMED_GREEN_200', 'name': 'Skyress Power Strike', 'price': 170, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'skyress'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 200}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Storm Skyress, gain +400 G-Power this battle.', 'effect_id': 'NAMED_GREEN_400', 'name': 'Storm Skyress Power Strike', 'price': 240, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'storm skyress'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 400}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Preyas II Angelo/Diablo, gain +400 G-Power this battle.', 'effect_id': 'NAMED_GREEN_400', 'name': 'Preyas II Angelo/Diablo Power Strike', 'price': 240, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'preyas ii angelo/diablo'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 400}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Ultimate Dragonoid, gain +400 G-Power this battle.', 'effect_id': 'NAMED_GREEN_400', 'name': 'Ultimate Dragonoid Power Strike', 'price': 240, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'ultimate dragonoid'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 400}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Neo Dragonoid, gain +400 G-Power this battle.', 'effect_id': 'NAMED_GREEN_400', 'name': 'Neo Dragonoid Power Strike', 'price': 240, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'neo dragonoid'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 400}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Ingram, gain +200 G-Power this battle.', 'effect_id': 'NAMED_GREEN_200', 'name': 'Ingram Power Strike', 'price': 170, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'ingram'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 200}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Master Ingram, gain +400 G-Power this battle.', 'effect_id': 'NAMED_GREEN_400', 'name': 'Master Ingram Power Strike', 'price': 240, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'master ingram'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 400}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Percival, gain +200 G-Power this battle.', 'effect_id': 'NAMED_GREEN_200', 'name': 'Percival Power Strike', 'price': 170, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'percival'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 200}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Knight Percival, gain +400 G-Power this battle.', 'effect_id': 'NAMED_GREEN_400', 'name': 'Knight Percival Power Strike', 'price': 240, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'knight percival'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 400}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Elfin, gain +200 G-Power this battle.', 'effect_id': 'NAMED_GREEN_200', 'name': 'Elfin Power Strike', 'price': 170, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'elfin'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 200}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Minx Elfin, gain +400 G-Power this battle.', 'effect_id': 'NAMED_GREEN_400', 'name': 'Minx Elfin Power Strike', 'price': 240, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'minx elfin'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 400}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Helios, gain +200 G-Power this battle.', 'effect_id': 'NAMED_GREEN_200', 'name': 'Helios Power Strike', 'price': 170, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'helios'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 200}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Viper Helios, gain +400 G-Power this battle.', 'effect_id': 'NAMED_GREEN_400', 'name': 'Viper Helios Power Strike', 'price': 240, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'viper helios'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 400}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Cyborg Helios, gain +400 G-Power this battle.', 'effect_id': 'NAMED_GREEN_400', 'name': 'Cyborg Helios Power Strike', 'price': 240, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'cyborg helios'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 400}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Nemus, gain +200 G-Power this battle.', 'effect_id': 'NAMED_GREEN_200', 'name': 'Nemus Power Strike', 'price': 170, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'nemus'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 200}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Mega Nemus, gain +400 G-Power this battle.', 'effect_id': 'NAMED_GREEN_400', 'name': 'Mega Nemus Power Strike', 'price': 240, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'mega nemus'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 400}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Brontes, gain +200 G-Power this battle.', 'effect_id': 'NAMED_GREEN_200', 'name': 'Brontes Power Strike', 'price': 170, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'brontes'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 200}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Mega Brontes, gain +400 G-Power this battle.', 'effect_id': 'NAMED_GREEN_400', 'name': 'Mega Brontes Power Strike', 'price': 240, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'mega brontes'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 400}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Wilda, gain +200 G-Power this battle.', 'effect_id': 'NAMED_GREEN_200', 'name': 'Wilda Power Strike', 'price': 170, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'wilda'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 200}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Thunder Wilda, gain +400 G-Power this battle.', 'effect_id': 'NAMED_GREEN_400', 'name': 'Thunder Wilda Power Strike', 'price': 240, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'thunder wilda'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 400}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Vulcan, gain +200 G-Power this battle.', 'effect_id': 'NAMED_GREEN_200', 'name': 'Vulcan Power Strike', 'price': 170, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'vulcan'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 200}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
    {'color': 'GREEN', 'description': 'If your battling Bakugan is Rex Vulcan, gain +400 G-Power this battle.', 'effect_id': 'NAMED_GREEN_400', 'name': 'Rex Vulcan Power Strike', 'price': 240, 'timing': 'DURING_BATTLE', 'custom_effect': {'timing': 'DURING_BATTLE', 'conditions': [{'type': 'self_name_contains', 'value': 'rex vulcan'}], 'actions': [{'type': 'add_g', 'target': 'self', 'amount': 400}], 'else_actions': []}, 'effect_mode': 'custom', 'restrictions': '', 'duration': ''},
]


RAW_ABILITY_CARDS = [
    {
        **card,
        'price': _priced_ability(card),
    }
    for card in RAW_ABILITY_CARDS
]