"""Ability card data."""

RAW_ABILITY_CARDS = [{'color': 'RED',
  'description': 'If your Bakugan has the lower original G-Power, it gets +100 G-Power this battle.',
  'effect_id': 'EXACT_A_HAND_UP',
  'name': 'A Hand Up',
  'price': 130,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [{'type': 'self_original_g_lower'}],
                    'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': "If the battle is on your opponent's Gate Card, your Bakugan gets +100 G-Power this battle.",
  'effect_id': 'ROLL_CHOOSE_BEST',
  'name': 'Brainwash',
  'price': 130,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [{'type': 'battle_on_opponent_gate'}],
                    'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': 'Reset both battling Bakugan to their original G-Powers before other battle bonuses this battle.',
  'effect_id': 'EXACT_CLEAN_SLATE',
  'name': 'Clean Slate',
  'price': 120,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'reset_both_to_original_g'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': 'Cancel attribute-based bonus effects for both battling Bakugan this battle.',
  'effect_id': 'EXACT_COLORVOID',
  'name': 'Colorvoid',
  'price': 120,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'block_attribute_effects', 'target': 'both'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': 'If this roll starts a battle, both players add one valid support Bakugan to the battle.',
  'effect_id': 'EXACT_COMBO_BATTLE',
  'name': 'Combo Battle',
  'price': 160,
  'timing': 'DURING_ROLL',
  'custom_effect': {'timing': 'DURING_ROLL',
                    'conditions': [],
                    'actions': [{'type': 'enable_combo_battle'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'If your opponent has more used Ability Cards than you, gain +100 G for Pyrus, +80 for Subterra or '
                 'Haos, and +50 for Aquos, Darkus, or Ventus.',
  'effect_id': 'EXACT_ALICES_SURPRISE',
  'name': "Alice's Surprise",
  'price': 180,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [{'type': 'opponent_used_more_abilities'}],
                    'actions': [{'type': 'add_g_by_attribute_map',
                                 'target': 'self',
                                 'map': {'PYRUS': 100,
                                         'SUBTERRA': 80,
                                         'HAOS': 80,
                                         'AQUOS': 50,
                                         'DARKUS': 50,
                                         'VENTUS': 50}}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'Gain G-Power based on the number of different Attributes among standing Bakugan on the field.',
  'effect_id': 'EXACT_BIG_BRAWL',
  'name': 'Big Brawl',
  'price': 180,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_by_distinct_field_attributes', 'target': 'self', 'scale': 40}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': "If the battle is on your opponent's Gate Card, +140 G-Power for Pyrus and +70 G-Power for Subterra",
  'effect_id': 'EXACT_BRUSHFIRE',
  'name': 'Brushfire',
  'price': 150,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [{'type': 'battle_on_opponent_gate'}],
                    'actions': [{'type': 'add_g_by_attribute_map',
                                 'target': 'self',
                                 'map': {'PYRUS': 140, 'SUBTERRA': 70}}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': "If the battle is on your opponent's Gate Card, +140 G for Darkus and +60 G for Haos.",
  'effect_id': 'EXACT_POWER_FROM_DARKNESS',
  'name': 'Power from Darkness',
  'price': 150,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [{'type': 'battle_on_opponent_gate'}],
                    'actions': [{'type': 'add_g_by_attribute_map',
                                 'target': 'self',
                                 'map': {'DARKUS': 140, 'HAOS': 60}}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'If your battling Bakugan is Aquos, replace it with one of your unused Bakugan at the start of the '
                 'battle.',
  'effect_id': 'EXACT_AQUOS_SWAP',
  'name': 'Aquos',
  'price': 160,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [{'type': 'self_attribute_is', 'value': 'AQUOS'}],
                    'actions': [{'type': 'replace_with_unused_bakugan'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'Move one of your other standing Bakugan into the battle as support if legal.',
  'effect_id': 'EXACT_ATTRACTOR',
  'name': 'Attractor',
  'price': 150,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [],
                    'actions': [{'type': 'summon_support_bakugan'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': "If your Bakugan has the lower original G-Power, swap the battling Bakugan's Attributes for this "
                 'battle.',
  'effect_id': 'EXACT_COLOR_SWAP',
  'name': 'Color Swap',
  'price': 150,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [{'type': 'self_original_g_lower'}],
                    'actions': [{'type': 'swap_attributes'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'The losing Bakugan is removed from the rest of the match.',
  'effect_id': 'EXACT_DOOM_CARD',
  'name': 'Doom Card',
  'price': 200,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE', 'conditions': [], 'actions': [{'type': 'doom_loser'}], 'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'Your opponent cannot use Green Ability Cards this battle.',
  'effect_id': 'EXACT_EARTH_SHUTDOWN',
  'name': 'Earth Shutdown',
  'price': 170,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [],
                    'actions': [{'type': 'block_color', 'target': 'opponent', 'color': 'GREEN'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': 'Improve this roll; if it starts a battle, your opponent cannot play Red Ability Cards in that '
                 'battle.',
  'effect_id': 'EXACT_LOCKDOWN',
  'name': 'Lockdown',
  'price': 110,
  'timing': 'DURING_ROLL',
  'custom_effect': {'timing': 'DURING_ROLL',
                    'conditions': [],
                    'actions': [{'type': 'improve_roll', 'amount': 0.12},
                                {'type': 'block_color_if_battle_starts', 'target': 'opponent', 'color': 'RED'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': 'If your Bakugan is Pyrus, improve this roll and gain +50 G if it starts a battle.',
  'effect_id': 'ROLL_BATTLE_BONUS',
  'name': 'Quickfire',
  'price': 110,
  'timing': 'DURING_ROLL',
  'custom_effect': {'timing': 'DURING_ROLL',
                    'conditions': [{'type': 'self_attribute_is', 'value': 'PYRUS'}],
                    'actions': [{'type': 'improve_roll', 'amount': 0.06},
                                {'type': 'add_g_on_battle_start', 'target': 'self', 'amount': 50}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': "If your opponent's Bakugan has the higher original G-Power, it loses 100 G-Power this battle.",
  'effect_id': 'EXACT_LEVEL_DOWN',
  'name': 'Level Down',
  'price': 110,
  'timing': 'DURING_ROLL',
  'custom_effect': {'timing': 'DURING_ROLL',
                    'conditions': [],
                    'actions': [{'type': 'pending_high_original_loses_g', 'amount': 100}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': 'If your Bakugan is Pyrus, gain +120 G-Power this battle.',
  'effect_id': 'EXACT_FIRE_JUDGE',
  'name': 'Fire Judge',
  'price': 110,
  'timing': 'DURING_ROLL',
  'custom_effect': {'timing': 'DURING_ROLL',
                    'conditions': [{'type': 'self_attribute_is', 'value': 'PYRUS'}],
                    'actions': [{'type': 'add_g_on_battle_start', 'target': 'self', 'amount': 120}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': 'Gain +80 G for Ventus and +50 G for Pyrus and Darkus this battle.',
  'effect_id': 'ROLL_BATTLE_BONUS',
  'name': 'Fire Wind',
  'price': 120,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_by_attribute_map',
                                 'target': 'self',
                                 'map': {'VENTUS': 80, 'PYRUS': 50, 'DARKUS': 50}}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'RED',
  'description': 'If this roll starts a battle, restart the battle and cancel other pending roll-based pre-battle '
                 'effects.',
  'effect_id': 'EXACT_DO_OVER',
  'name': 'Do Over',
  'price': 120,
  'timing': 'DURING_ROLL',
  'custom_effect': {'timing': 'DURING_ROLL',
                    'conditions': [],
                    'actions': [{'type': 'pending_do_over'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Haos gets +80 G-Power; Subterra and Darkus get +50 G-Power this battle.',
  'effect_id': 'EXACT_LEGENDS_OF_LIGHT',
  'name': 'Legends of Light',
  'price': 160,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_by_attribute_map',
                                 'target': 'self',
                                 'map': {'HAOS': 80, 'SUBTERRA': 50, 'DARKUS': 50}}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Darkus gets +80 G, Haos and Ventus get +50 G this battle.',
  'effect_id': 'BATTLE_DARKUS_BOOST',
  'name': 'Legends of Darkness',
  'price': 160,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_by_attribute_map',
                                 'target': 'self',
                                 'map': {'DARKUS': 80, 'HAOS': 50, 'VENTUS': 50}}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Ventus gets +80 G-Power; Pyrus and Darkus get +50 G-Power this battle.',
  'effect_id': 'EXACT_LEGENDS_OF_WIND',
  'name': 'Legends of Wind',
  'price': 150,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_by_attribute_map',
                                 'target': 'self',
                                 'map': {'VENTUS': 80, 'PYRUS': 50, 'DARKUS': 50}}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Pyrus gets +80 G, Aquos and Ventus get +50 G this battle.',
  'effect_id': 'BATTLE_PYRUS_BOOST',
  'name': 'Legends of Fire',
  'price': 150,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_by_attribute_map',
                                 'target': 'self',
                                 'map': {'PYRUS': 80, 'AQUOS': 50, 'VENTUS': 50}}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Gain +100 G-Power if you have both a Blue and a Green Ability Card in your used pile.',
  'effect_id': 'EXACT_BLUE_GREEN_COMBINE',
  'name': 'Blue-Green Combine',
  'price': 170,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [{'type': 'used_colors_include', 'value': ['BLUE', 'GREEN']}],
                    'actions': [{'type': 'add_g', 'target': 'self', 'amount': 100}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'All of your standing Bakugan gain +50 G-Power this battle.',
  'effect_id': 'EXACT_BOOST_ALL',
  'name': 'Boost All',
  'price': 130,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_to_all_friendly_standing', 'amount': 50}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'If your Bakugan is Darkus, gain +120 G-Power this battle.',
  'effect_id': 'EXACT_DARKUS_ONLY',
  'name': 'Darkus',
  'price': 150,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [{'type': 'self_attribute_is', 'value': 'DARKUS'}],
                    'actions': [{'type': 'add_g', 'target': 'self', 'amount': 120}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'If your Bakugan is Aquos, gain +120 G-Power this battle.',
  'effect_id': 'EXACT_AQUOS_ONLY',
  'name': 'Aquos 2',
  'price': 140,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [{'type': 'self_attribute_is', 'value': 'AQUOS'}],
                    'actions': [{'type': 'add_g', 'target': 'self', 'amount': 120}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'Your opponent cannot use Haos-based Ability effects this battle.',
  'effect_id': 'GREEN_BLOCK_ENEMY',
  'name': 'Light Shutdown',
  'price': 140,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [],
                    'actions': [{'type': 'block_attribute_effects_for_attribute',
                                 'target': 'opponent',
                                 'attribute': 'HAOS'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'Your opponent cannot use Ventus-based Ability effects this battle.',
  'effect_id': 'GREEN_BLOCK_ENEMY',
  'name': 'Wind Shutdown',
  'price': 140,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [],
                    'actions': [{'type': 'block_attribute_effects_for_attribute',
                                 'target': 'opponent',
                                 'attribute': 'VENTUS'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': "Swap the battling Bakugan's original G-Powers for this battle.",
  'effect_id': 'EXACT_SWAP_ORIGINAL_G',
  'name': 'Preyas Switch',
  'price': 160,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [],
                    'actions': [{'type': 'swap_original_g'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'GREEN',
  'description': 'Return one of your used Ability Cards to your unused pile.',
  'effect_id': 'EXACT_RETURN_USED_ABILITY',
  'name': 'Help From Friends',
  'price': 150,
  'timing': 'FLEXIBLE',
  'custom_effect': {'timing': 'FLEXIBLE',
                    'conditions': [],
                    'actions': [{'type': 'return_one_used_ability'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Your Bakugan gets double Gate Card bonus this battle.',
  'effect_id': 'EXACT_DOUBLE_GATE_BONUS',
  'name': 'Bright Light',
  'price': 150,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'If your Bakugan is a Dragonoid, it gets double Gate Card bonus this battle.',
  'effect_id': 'EXACT_DRAGONOID_DOUBLE_GATE',
  'name': 'Dragonoid Charge',
  'price': 160,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [{'type': 'self_name_contains', 'value': 'dragonoid'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Gain 50 G for each Gate Card you have won this match.',
  'effect_id': 'EXACT_GATE_WON_SCALING',
  'name': 'Bee Striker',
  'price': 150,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_by_gates_won', 'target': 'self', 'scale': 50}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Gain 40 G for each Ability Card in your used pile.',
  'effect_id': 'EXACT_USED_ABILITY_SCALING',
  'name': 'Dark Growth',
  'price': 150,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_by_used_abilities', 'target': 'self', 'scale': 40}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Gain a random G-Power bonus from 0 to 100 this battle.',
  'effect_id': 'EXACT_CAROUSEL_T1',
  'name': 'Carousel Tier 1',
  'price': 120,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_random_g', 'target': 'self', 'min': 0, 'max': 100}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Gain a random G-Power bonus from 0 to 250 this battle.',
  'effect_id': 'EXACT_CAROUSEL_T2',
  'name': 'Carousel Tier 2',
  'price': 170,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_random_g', 'target': 'self', 'min': 0, 'max': 250}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''},
 {'color': 'BLUE',
  'description': 'Gain a random G-Power bonus from 0 to 400 this battle.',
  'effect_id': 'EXACT_CAROUSEL_T3',
  'name': 'Carousel Tier 3',
  'price': 220,
  'timing': 'DURING_BATTLE',
  'custom_effect': {'timing': 'DURING_BATTLE',
                    'conditions': [],
                    'actions': [{'type': 'add_random_g', 'target': 'self', 'min': 0, 'max': 400}],
                    'else_actions': []},
  'effect_mode': 'custom',
  'restrictions': '',
  'duration': ''}]
