"""Bakugan template data."""

RAW_BAKUGAN_TEMPLATES = [{'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 440,
  'min_g_power': 190,
  'name': 'Serpenoid',
  'price': 100},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 450,
  'min_g_power': 200,
  'name': 'Juggernoid',
  'price': 100},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 450,
  'min_g_power': 200,
  'name': 'Robotallion',
  'price': 100},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 460,
  'min_g_power': 210,
  'name': 'Saurus',
  'price': 105},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 460,
  'min_g_power': 210,
  'name': 'Falconeer',
  'price': 105},
 {'allowed_attributes': ['SUBTERRA', 'HAOS', 'VENTUS'],
  'max_g_power': 550,
  'min_g_power': 300,
  'name': 'Manion',
  'price': 150},
 {'allowed_attributes': ['PYRUS', 'HAOS', 'VENTUS'],
  'max_g_power': 550,
  'min_g_power': 300,
  'name': 'Ravenoid',
  'price': 150},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 480,
  'min_g_power': 230,
  'name': 'Stinglash',
  'price': 115},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 490,
  'min_g_power': 240,
  'name': 'Centipoid',
  'price': 120},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'DARKUS', 'VENTUS'],
  'max_g_power': 500,
  'min_g_power': 250,
  'name': 'Gargonoid',
  'price': 125},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 520,
  'min_g_power': 270,
  'name': 'Fear Ripper',
  'price': 135},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 520,
  'min_g_power': 270,
  'name': 'Siege',
  'price': 135},
 {'allowed_attributes': ['PYRUS', 'HAOS', 'VENTUS'],
  'max_g_power': 550,
  'min_g_power': 300,
  'name': 'Monarus',
  'price': 150},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 550,
  'min_g_power': 300,
  'name': 'Griffon',
  'price': 150},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS'],
  'max_g_power': 570,
  'min_g_power': 320,
  'name': 'Terrorclaw',
  'price': 160},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 620,
  'min_g_power': 370,
  'name': 'Laserman',
  'price': 185},
 {'allowed_attributes': ['AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 630,
  'min_g_power': 380,
  'name': 'Reaper',
  'price': 190},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 670,
  'min_g_power': 420,
  'name': 'Leonidas',
  'price': 250},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 900,
  'min_g_power': 650,
  'name': 'Omega Leonidas',
  'price': 405},
 {'allowed_attributes': ['PYRUS'], 'max_g_power': 640, 'min_g_power': 390, 'name': 'Fourtress', 'price': 195},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 650,
  'min_g_power': 400,
  'name': 'Dragonoid',
  'price': 250},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 750,
  'min_g_power': 500,
  'name': 'Delta Dragonoid II',
  'price': 340},
 {'allowed_attributes': ['AQUOS'], 'max_g_power': 640, 'min_g_power': 390, 'name': 'Sirenoid', 'price': 195},
 {'allowed_attributes': ['AQUOS'], 'max_g_power': 630, 'min_g_power': 380, 'name': 'Preyas', 'price': 190},
 {'allowed_attributes': ['SUBTERRA'], 'max_g_power': 640, 'min_g_power': 390, 'name': 'Cycloid', 'price': 195},
 {'allowed_attributes': ['SUBTERRA'], 'max_g_power': 650, 'min_g_power': 400, 'name': 'Gorem', 'price': 200},
 {'allowed_attributes': ['SUBTERRA'], 'max_g_power': 750, 'min_g_power': 500, 'name': 'Hammer Gorem', 'price': 250},
 {'allowed_attributes': ['HAOS'], 'max_g_power': 640, 'min_g_power': 390, 'name': 'Tentaclear', 'price': 195},
 {'allowed_attributes': ['HAOS'], 'max_g_power': 650, 'min_g_power': 400, 'name': 'Tigrerra', 'price': 200},
 {'allowed_attributes': ['HAOS'], 'max_g_power': 750, 'min_g_power': 500, 'name': 'Blade Tigrerra', 'price': 250},
 {'allowed_attributes': ['DARKUS'], 'max_g_power': 700, 'min_g_power': 450, 'name': 'Hydranoid', 'price': 225},
 {'allowed_attributes': ['DARKUS'], 'max_g_power': 800, 'min_g_power': 550, 'name': 'Dual Hydranoid', 'price': 325},
 {'allowed_attributes': ['DARKUS'], 'max_g_power': 670, 'min_g_power': 420, 'name': 'Vladitor', 'price': 300},
 {'allowed_attributes': ['DARKUS'], 'max_g_power': 900, 'min_g_power': 650, 'name': 'Battle Ax Vladitor', 'price': 450},
 {'allowed_attributes': ['VENTUS'], 'max_g_power': 640, 'min_g_power': 390, 'name': 'Harpus', 'price': 195},
 {'allowed_attributes': ['VENTUS'], 'max_g_power': 650, 'min_g_power': 400, 'name': 'Skyress', 'price': 200},
 {'allowed_attributes': ['VENTUS'], 'max_g_power': 750, 'min_g_power': 500, 'name': 'Storm Skyress', 'price': 250},
 {'allowed_attributes': ['AQUOS'],
  'max_g_power': 500,
  'min_g_power': 450,
  'name': 'Angelo/Diablo Preyas',
  'price': 280},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 550,
  'min_g_power': 500,
  'name': 'Ultimate Dragonoid',
  'price': 420},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 550,
  'min_g_power': 500,
  'name': 'Neo Dragonoid',
  'price': 430},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 580,
  'min_g_power': 540,
  'name': 'Cross Dragonoid',
  'price': 500},
 {'allowed_attributes': ['PYRUS', 'AQUOS', 'SUBTERRA', 'HAOS', 'DARKUS', 'VENTUS'],
  'max_g_power': 600,
  'min_g_power': 560,
  'name': 'Helix Dragonoid',
  'price': 560},
 {'allowed_attributes': ['VENTUS'], 'max_g_power': 540, 'min_g_power': 500, 'name': 'Master Ingram', 'price': 430},
 {'allowed_attributes': ['DARKUS'], 'max_g_power': 540, 'min_g_power': 500, 'name': 'Knight Percival', 'price': 430},
 {'allowed_attributes': ['AQUOS'], 'max_g_power': 540, 'min_g_power': 500, 'name': 'Minx Elfin', 'price': 430},
 {'allowed_attributes': ['DARKUS'], 'max_g_power': 540, 'min_g_power': 500, 'name': 'Viper Helios', 'price': 430},
 {'allowed_attributes': ['DARKUS'], 'max_g_power': 580, 'min_g_power': 540, 'name': 'Cyborg Helios', 'price': 510},
 {'allowed_attributes': ['SUBTERRA'], 'max_g_power': 540, 'min_g_power': 500, 'name': 'Rex Vulcan', 'price': 430}]
