"""Gate card data."""

RAW_GATE_CARDS = [{'bonuses': {'PYRUS': 180, 'AQUOS': 60, 'SUBTERRA': 90, 'HAOS': 140, 'DARKUS': 130, 'VENTUS': 50},
  'description': 'Serpenoid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Serpenoid',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 80, 'AQUOS': 160, 'SUBTERRA': 70, 'HAOS': 100, 'DARKUS': 70, 'VENTUS': 40},
  'description': 'Juggernoid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Juggernoid',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 160, 'AQUOS': 110, 'SUBTERRA': 90, 'HAOS': 120, 'DARKUS': 90, 'VENTUS': 40},
  'description': 'Robotallion gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Robotallion',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 100, 'AQUOS': 50, 'SUBTERRA': 180, 'HAOS': 100, 'DARKUS': 50, 'VENTUS': 80},
  'description': 'Saurus gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Saurus',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 80, 'AQUOS': 100, 'SUBTERRA': 80, 'HAOS': 70, 'DARKUS': 80, 'VENTUS': 160},
  'description': 'Falconeer gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Falconeer',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 160, 'AQUOS': 100, 'SUBTERRA': 70, 'HAOS': 70, 'DARKUS': 90, 'VENTUS': 70},
  'description': 'Warius gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Warius',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 60, 'AQUOS': 50, 'SUBTERRA': 150, 'HAOS': 70, 'DARKUS': 10, 'VENTUS': 130},
  'description': 'Manion gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Manion',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 90, 'AQUOS': 60, 'SUBTERRA': 70, 'HAOS': 130, 'DARKUS': 30, 'VENTUS': 180},
  'description': 'Ravenoid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Ravenoid',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 80, 'AQUOS': 90, 'SUBTERRA': 130, 'HAOS': 50, 'DARKUS': 150, 'VENTUS': 50},
  'description': 'Stinglash gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Stinglash',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 70, 'AQUOS': 40, 'SUBTERRA': 140, 'HAOS': 130, 'DARKUS': 160, 'VENTUS': 100},
  'description': 'Centipoid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Centipoid',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 160, 'AQUOS': 110, 'SUBTERRA': 70, 'HAOS': 40, 'DARKUS': 70, 'VENTUS': 160},
  'description': 'Gargonoid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Gargonoid',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 90, 'AQUOS': 110, 'SUBTERRA': 90, 'HAOS': 170, 'DARKUS': 70, 'VENTUS': 80},
  'description': 'Fear Ripper gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Fear Ripper',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 70, 'AQUOS': 170, 'SUBTERRA': 60, 'HAOS': 100, 'DARKUS': 60, 'VENTUS': 50},
  'description': 'Siege gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Siege',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 30, 'AQUOS': 50, 'SUBTERRA': 70, 'HAOS': 80, 'DARKUS': 20, 'VENTUS': 180},
  'description': 'Monarus gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Monarus',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 140, 'AQUOS': 120, 'SUBTERRA': 100, 'HAOS': 130, 'DARKUS': 50, 'VENTUS': 80},
  'description': 'Griffon gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Griffon',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 40, 'AQUOS': 180, 'SUBTERRA': 90, 'HAOS': 40, 'DARKUS': 40, 'VENTUS': 80},
  'description': 'Terrorclaw gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Terrorclaw',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 80, 'AQUOS': 100, 'SUBTERRA': 130, 'HAOS': 90, 'DARKUS': 180, 'VENTUS': 130},
  'description': 'Laserman gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Laserman',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 100, 'AQUOS': 100, 'SUBTERRA': 100, 'HAOS': 100, 'DARKUS': 100, 'VENTUS': 100},
  'description': 'Leonidas gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Leonidas',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 200, 'AQUOS': 200, 'SUBTERRA': 200, 'HAOS': 200, 'DARKUS': 200, 'VENTUS': 200},
  'description': 'Omega Leonidas gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Omega Leonidas',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 20, 'AQUOS': 20, 'SUBTERRA': 20, 'HAOS': 20, 'DARKUS': 150, 'VENTUS': 20},
  'description': 'Vladitor gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Vladitor',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 10, 'AQUOS': 10, 'SUBTERRA': 10, 'HAOS': 10, 'DARKUS': 200, 'VENTUS': 10},
  'description': 'Battle Ax Vladitor gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Battle Ax Vladitor',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 150, 'AQUOS': 50, 'SUBTERRA': 70, 'HAOS': 30, 'DARKUS': 50, 'VENTUS': 40},
  'description': 'Dragonoid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Dragonoid',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 200, 'AQUOS': 100, 'SUBTERRA': 150, 'HAOS': 50, 'DARKUS': 100, 'VENTUS': 50},
  'description': 'Delta Dragonoid II gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Delta Dragonoid II',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 180, 'AQUOS': 110, 'SUBTERRA': 170, 'HAOS': 130, 'DARKUS': 100, 'VENTUS': 140},
  'description': 'Fourtress gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Fourtress',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 10, 'AQUOS': 150, 'SUBTERRA': 150, 'HAOS': 20, 'DARKUS': 150, 'VENTUS': 10},
  'description': 'Preyas gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Preyas',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 100, 'AQUOS': 200, 'SUBTERRA': 180, 'HAOS': 50, 'DARKUS': 180, 'VENTUS': 10},
  'description': 'Preyas II gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Preyas II',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 150, 'AQUOS': 180, 'SUBTERRA': 110, 'HAOS': 120, 'DARKUS': 70, 'VENTUS': 130},
  'description': 'Sirenoid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Sirenoid',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 80, 'AQUOS': 10, 'SUBTERRA': 150, 'HAOS': 20, 'DARKUS': 30, 'VENTUS': 50},
  'description': 'Gorem gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Gorem',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 150, 'AQUOS': 90, 'SUBTERRA': 200, 'HAOS': 120, 'DARKUS': 70, 'VENTUS': 130},
  'description': 'Hammer Gorem gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Hammer Gorem',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 150, 'AQUOS': 120, 'SUBTERRA': 180, 'HAOS': 120, 'DARKUS': 100, 'VENTUS': 60},
  'description': 'Cycloid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Cycloid',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 50, 'AQUOS': 50, 'SUBTERRA': 90, 'HAOS': 150, 'DARKUS': 20, 'VENTUS': 10},
  'description': 'Tigrerra gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Tigrerra',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 50, 'AQUOS': 40, 'SUBTERRA': 90, 'HAOS': 200, 'DARKUS': 150, 'VENTUS': 60},
  'description': 'Blade Tigrerra gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Blade Tigrerra',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 120, 'AQUOS': 100, 'SUBTERRA': 150, 'HAOS': 180, 'DARKUS': 100, 'VENTUS': 50},
  'description': 'Tentaclear gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Tentaclear',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 20, 'AQUOS': 40, 'SUBTERRA': 10, 'HAOS': 10, 'DARKUS': 150, 'VENTUS': 50},
  'description': 'Hydranoid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Hydranoid',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 70, 'AQUOS': 90, 'SUBTERRA': 130, 'HAOS': 130, 'DARKUS': 200, 'VENTUS': 60},
  'description': 'Dual Hydranoid gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Dual Hydranoid',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 100, 'AQUOS': 50, 'SUBTERRA': 150, 'HAOS': 70, 'DARKUS': 200, 'VENTUS': 140},
  'description': 'Reaper gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Reaper',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 20, 'AQUOS': 50, 'SUBTERRA': 50, 'HAOS': 50, 'DARKUS': 70, 'VENTUS': 150},
  'description': 'Skyress gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Skyress',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 150, 'AQUOS': 50, 'SUBTERRA': 60, 'HAOS': 90, 'DARKUS': 40, 'VENTUS': 200},
  'description': 'Storm Skyress gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Storm Skyress',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 120, 'AQUOS': 140, 'SUBTERRA': 100, 'HAOS': 110, 'DARKUS': 90, 'VENTUS': 180},
  'description': 'Harpus gets the Gate Card bonus twice',
  'effect_id': 'GATE_DOUBLE_BONUS_NAMED',
  'gate_type': 'GOLD',
  'name': 'Harpus',
  'price': 130,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'named_bakugan_matches_gate'}],
                    'actions': [{'type': 'double_gate_bonus', 'target': 'self'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 140, 'AQUOS': 120, 'SUBTERRA': 80, 'HAOS': 20, 'DARKUS': 20, 'VENTUS': 60},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Fire Pit',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 20, 'AQUOS': 60, 'SUBTERRA': 140, 'HAOS': 120, 'DARKUS': 80, 'VENTUS': 20},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Muddy Ground',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 50, 'AQUOS': 50, 'SUBTERRA': 90, 'HAOS': 200, 'DARKUS': 170, 'VENTUS': 110},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Light-Burst',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 20, 'AQUOS': 170, 'SUBTERRA': 110, 'HAOS': 80, 'DARKUS': 110, 'VENTUS': 50},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Tsunami',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 80, 'AQUOS': 20, 'SUBTERRA': 20, 'HAOS': 60, 'DARKUS': 140, 'VENTUS': 120},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Dusk',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 110, 'AQUOS': 120, 'SUBTERRA': 120, 'HAOS': 110, 'DARKUS': 120, 'VENTUS': 120},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'High Energy',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 90, 'AQUOS': 200, 'SUBTERRA': 170, 'HAOS': 110, 'DARKUS': 50, 'VENTUS': 50},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Whirlpool',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 60, 'AQUOS': 150, 'SUBTERRA': 120, 'HAOS': 50, 'DARKUS': 20, 'VENTUS': 20},
  'description': 'None',
  'effect_id': 'GATE_AQUOS_FOCUS',
  'gate_type': 'SILVER',
  'name': 'Aquos Vortex',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_if_attribute', 'target': 'both', 'attribute': 'AQUOS', 'amount': 50}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 60, 'AQUOS': 140, 'SUBTERRA': 120, 'HAOS': 80, 'DARKUS': 20, 'VENTUS': 40},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Heavy Surf',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 90, 'AQUOS': 110, 'SUBTERRA': 100, 'HAOS': 90, 'DARKUS': 110, 'VENTUS': 100},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Elevated Field',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 50, 'AQUOS': 90, 'SUBTERRA': 200, 'HAOS': 170, 'DARKUS': 110, 'VENTUS': 50},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Earthen Mound',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 110, 'AQUOS': 80, 'SUBTERRA': 110, 'HAOS': 50, 'DARKUS': 20, 'VENTUS': 170},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Sand Storm',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 120, 'AQUOS': 100, 'SUBTERRA': 150, 'HAOS': 50, 'DARKUS': 100, 'VENTUS': 50},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'The Cliffs',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 120, 'AQUOS': 100, 'SUBTERRA': 150, 'HAOS': 50, 'DARKUS': 100, 'VENTUS': 50},
  'description': 'None',
  'effect_id': 'GATE_LOW_G_ADVANTAGE',
  'gate_type': 'SILVER',
  'name': 'Black Hole',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_to_lower_current', 'amount': 80}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 170, 'AQUOS': 110, 'SUBTERRA': 50, 'HAOS': 50, 'DARKUS': 90, 'VENTUS': 180},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Tornado Alley',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 120, 'AQUOS': 80, 'SUBTERRA': 20, 'HAOS': 40, 'DARKUS': 60, 'VENTUS': 140},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Force Wind',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 50, 'AQUOS': 40, 'SUBTERRA': 40, 'HAOS': 110, 'DARKUS': 70, 'VENTUS': 150},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'The Spires',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 50, 'AQUOS': 20, 'SUBTERRA': 50, 'HAOS': 60, 'DARKUS': 20, 'VENTUS': 70},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Wind Farm',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 50, 'AQUOS': 40, 'SUBTERRA': 40, 'HAOS': 110, 'DARKUS': 70, 'VENTUS': 150},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Blue Sky',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 50, 'AQUOS': 20, 'SUBTERRA': 50, 'HAOS': 60, 'DARKUS': 20, 'VENTUS': 70},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Vacuum',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 200, 'AQUOS': 170, 'SUBTERRA': 110, 'HAOS': 50, 'DARKUS': 50, 'VENTUS': 90},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Volcanic Lake',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 140, 'AQUOS': 120, 'SUBTERRA': 80, 'HAOS': 20, 'DARKUS': 40, 'VENTUS': 60},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Powder Keg',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 140, 'AQUOS': 120, 'SUBTERRA': 80, 'HAOS': 20, 'DARKUS': 40, 'VENTUS': 60},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Earthen Wave',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 50, 'AQUOS': 60, 'SUBTERRA': 20, 'HAOS': 70, 'DARKUS': 50, 'VENTUS': 20},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Low Energy',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 20, 'AQUOS': 20, 'SUBTERRA': 60, 'HAOS': 140, 'DARKUS': 120, 'VENTUS': 80},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Sunrise',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 60, 'AQUOS': 150, 'SUBTERRA': 120, 'HAOS': 50, 'DARKUS': 20, 'VENTUS': 20},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Spitting Fire',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 60, 'AQUOS': 140, 'SUBTERRA': 120, 'HAOS': 80, 'DARKUS': 20, 'VENTUS': 40},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Sun Spot',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 110, 'AQUOS': 50, 'SUBTERRA': 50, 'HAOS': 90, 'DARKUS': 200, 'VENTUS': 170},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Haunted Night',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 100, 'AQUOS': 50, 'SUBTERRA': 120, 'HAOS': 100, 'DARKUS': 150, 'VENTUS': 50},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Pit Dweller',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 80, 'AQUOS': 70, 'SUBTERRA': 20, 'HAOS': 120, 'DARKUS': 170, 'VENTUS': 120},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Nightmare',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 80, 'AQUOS': 70, 'SUBTERRA': 20, 'HAOS': 120, 'DARKUS': 170, 'VENTUS': 120},
  'description': 'None',
  'effect_id': 'GATE_EXACT_NONE',
  'gate_type': 'SILVER',
  'name': 'Fields Of Lava',
  'price': 110,
  'custom_effect': {'timing': 'PASSIVE_GATE', 'conditions': [], 'actions': [], 'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 110, 'AQUOS': 100, 'SUBTERRA': 80, 'HAOS': 70, 'DARKUS': 50, 'VENTUS': 40},
  'description': 'All G-Power boosts from Ability Cards are doubled',
  'effect_id': 'GATE_EXACT_DOUBLE_ABILITY_BOOSTS',
  'gate_type': 'BRONZE',
  'name': 'Lockdown',
  'price': 120,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [],
                    'actions': [{'type': 'double_ability_boosts', 'target': 'both'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 60, 'AQUOS': 30, 'SUBTERRA': 50, 'HAOS': 20, 'DARKUS': 20, 'VENTUS': 40},
  'description': "Each battling Bakugan's original G-Power is swapped",
  'effect_id': 'GATE_EXACT_SWAP_ORIGINAL_G',
  'gate_type': 'BRONZE',
  'name': 'G-Power Exchange',
  'price': 120,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [],
                    'actions': [{'type': 'swap_original_g'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 100, 'AQUOS': 40, 'SUBTERRA': 50, 'HAOS': 110, 'DARKUS': 150, 'VENTUS': 50},
  'description': 'Each battling Bakugan gains 100 G for each Gate Card its side has won this match',
  'effect_id': 'GATE_EXACT_GATE_WON_SCALING',
  'gate_type': 'BRONZE',
  'name': 'Mega Warrior',
  'price': 120,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_by_gates_won', 'target': 'both', 'scale': 100}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 140, 'AQUOS': 80, 'SUBTERRA': 50, 'HAOS': 80, 'DARKUS': 60, 'VENTUS': 20},
  'description': 'Neither side can play Ability Cards this battle',
  'effect_id': 'GATE_EXACT_NO_ABILITIES',
  'gate_type': 'BRONZE',
  'name': 'Stand Off',
  'price': 120,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [],
                    'actions': [{'type': 'prevent_abilities', 'target': 'both'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 20, 'AQUOS': 80, 'SUBTERRA': 140, 'HAOS': 50, 'DARKUS': 60, 'VENTUS': 110},
  'description': 'Both players return all used Ability Cards to their unused pile',
  'effect_id': 'GATE_EXACT_RETURN_ALL_USED',
  'gate_type': 'BRONZE',
  'name': 'Stand Your Ground',
  'price': 120,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [],
                    'actions': [{'type': 'return_all_used_abilities'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 110, 'AQUOS': 80, 'SUBTERRA': 60, 'HAOS': 90, 'DARKUS': 120, 'VENTUS': 140},
  'description': 'Each battling Bakugan gains 100 G for each Ability Card its side has used this match',
  'effect_id': 'GATE_EXACT_ABILITY_USED_SCALING',
  'gate_type': 'BRONZE',
  'name': 'Trick Jump',
  'price': 120,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [],
                    'actions': [{'type': 'add_g_by_used_abilities', 'target': 'both', 'scale': 100}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 80, 'AQUOS': 90, 'SUBTERRA': 50, 'HAOS': 50, 'DARKUS': 60, 'VENTUS': 80},
  'description': 'The Bakugan with the lower original G-Power has its original G-Power doubled',
  'effect_id': 'GATE_EXACT_DOUBLE_LOWER_ORIGINAL_G',
  'gate_type': 'BRONZE',
  'name': 'Overtake',
  'price': 120,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [],
                    'actions': [{'type': 'double_lower_original_g'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 110, 'AQUOS': 170, 'SUBTERRA': 110, 'HAOS': 140, 'DARKUS': 170, 'VENTUS': 140},
  'description': 'The Bakugan with the lower original G-Power has its original G-Power doubled',
  'effect_id': 'GATE_EXACT_DOUBLE_LOWER_ORIGINAL_G',
  'gate_type': 'BRONZE',
  'name': 'Reflexes',
  'price': 120,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [],
                    'actions': [{'type': 'double_lower_original_g'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''},
 {'bonuses': {'PYRUS': 110, 'AQUOS': 100, 'SUBTERRA': 80, 'HAOS': 70, 'DARKUS': 50, 'VENTUS': 40},
  'description': 'If either battling Bakugan is Aquos, their original G-Powers are swapped',
  'effect_id': 'GATE_EXACT_SWAP_ORIGINAL_G_IF_AQUOS',
  'gate_type': 'BRONZE',
  'name': 'Power Siphon',
  'price': 120,
  'custom_effect': {'timing': 'PASSIVE_GATE',
                    'conditions': [{'type': 'either_attribute_is', 'value': 'AQUOS'}],
                    'actions': [{'type': 'swap_original_g'}],
                    'else_actions': []},
  'effect_mode': 'builtin',
  'restrictions': '',
  'duration': ''}]
